name: vault
baseurl: /vault
description: Type-safe, persistent storage for values of arbitrary types
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 3.0.0-RC2
org: Christopher Davenport
markdown: kramdown
