name: vault
baseurl: /vault
description: Type-safe, persistent storage for values of arbitrary types
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 2.0.0-RC2+6-3592439e-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
